---
kind: pipeline
name: deploy to swarm.autonomic.zone
steps:
  - name: bundle static
    image: plugins/docker
    settings:
      username: thecoopcloud
      password:
        from_secret: thecoopcloud_password
      repo: thecoopcloud/docs.coopcloud.tech
      tags: latest

  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      stack: coop_cloud_mkdocs
      deploy_key:
        from_secret: drone_ssh_swarm.autonomic.zone

  - name: notify coopcloud-dev on failure
    image: plugins/matrix
    settings:
      homeserver: https://matrix.autonomic.zone
      roomid: "IFazIpLtxiScqbHqoa:autonomic.zone"
      userid: "@autono-bot:autonomic.zone"
      accesstoken:
        from_secret: autono_bot_access_token
    depends_on:
      - bundle static
      - deployment
    when:
      status:
        - failure
trigger:
  branch:
    - main
